apiVersion: v1
kind: Service
metadata:
  name: mq-service
spec:
  selector:
    pod: mq
  ports:
  - protocol: TCP
    name: tesla1
    port: 5672
    targetPort: 5672
  - protocol: TCP
    name: tesla2
    port: 15672
    targetPort: 15672

---

kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
