apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: django
  annotations:
    "helm.sh/hook-weight": "510000"
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-k8
          image: {{ .Values.image.repository  }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-service

            - name: MQ_HOST
              value: mq-service

            - name: ENV
              value: k8
      imagePullSecrets:
      - name: regcred

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: celery-worker
  annotations:
    "helm.sh/hook-weight": "5"
  labels:
    deployment: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: {{ .Values.image.repository  }}
          imagePullPolicy: Always
          command: ["./run_celery.sh"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-service

            - name: MQ_HOST
              value: mq-service

            - name: ENV
              value: k8
      imagePullSecrets:
      - name: regcred

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flower
  annotations:
    "helm.sh/hook-weight": "5"
  labels:
    deployment: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-flower
  template:
    metadata:
      labels:
        pod: celery-flower
    spec:
      containers:
      - name: flower
        image: {{ .Values.image.repository  }}
        imagePullPolicy: Always
        command: ['celery', 'flower', '-A', 'modana', 'flower']
        ports:
          - containerPort: 5555
        env:
            - name: MQ_HOST
              value: mq-service

            - name: ENV
              value: k8
      imagePullSecrets:
      - name: regcred

